# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ios-sdk-example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NeuosAsPodTest
	pod 'NeuosSDK', :path => '/Users/shai/repos/neuos-ios-framework/NeuosSDK'

end
